server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wiseconnect
    username: root 
    password: admin

  jpa:
    database: mysql
    show-sql: true

